learning_templates/basic_app/urls.py
from django.urls import path
from . import views

#TEMPLATE TAGGING
app_name = 'basic_app'


urlpatterns = [
path('', views.index, name='index'),
path('other/', views.other, name='other'),
path('relative/', views.realtive, name='realtive')



]
           

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
    path('relative/', include('basic_app.urls')),
    path('other/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def realtive(request):
    return render(request, 'basic_app/relative_url_templates.html')        

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-brand"><a href="{% url 'basic_app:index' %}">BRAND</a></li>
                <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
                <li class="navbar-link"><a href="{% url 'basic_app:other' %}">Other</a></li>

            </ul>

        </div>

    </nav>
    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>
    
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
   {% block body_block %}
      <h1>WELCOME TO INDEX!</h1>
      <h2>This is index.html page showing</h2>
      <h3>{{ text|cut:'world' }}</h3>
      <h3> {{ number|add:"99" }}</h3>
   {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
   {% block body_block %}
      <h1>WELCOME TO OTHER!</h1>
      <h2>This is an example of inheritance</h2>
   {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a><br>
    <a href="{% url 'admin:index' %}">link to admin</a><br>
    <a href="{% url 'basic_app:index' %}">link to index</a>
</body>
</html>